import { brown, makeLoop, mulberry32, normRms, pink, white, type Rng } from "./dsp";

/** Everything a layer needs to know about the ride, already defaulted and clamped. */
export interface RideState {
  speed: number; // m/s
  crank: number; // crank revolutions / s
  wheel: number; // wheel revolutions / s
  pedal: number; // 0 coasting … 1 pedalling
  brake: number; // 0 … 1
  steer: number; // -1 left … 1 right
  bump: number; // impulse strength this frame (0 = none)
  roughness: number; // 0 smooth asphalt … 1 rough
  water: number; // proximity to paddies / irrigation water 0…1
  trees: number; // proximity to trees / foliage 0…1
  houses: number; // proximity to houses 0…1
  evening: number; // 0 midday … 1 dusk
}

/** Shared environment signals computed once per tick by the engine. */
export interface Env {
  gust: number; // 0 calm … 1 strong gust
  turb: number; // fast turbulence 0…1
}

export interface PlayOpts {
  gain?: number;
  pan?: number;
  panTo?: number;
  rate?: number;
  dest: AudioNode;
  wet?: number;
  wetDest?: AudioNode;
}

/** Sample rate for pre-rendered voices (content stays below ~12 kHz). */
export const GEN_SR = 32000;

export class Kit {
  readonly rng: Rng;
  readonly white: AudioBuffer;
  readonly pink: AudioBuffer;
  readonly pinkSt: AudioBuffer;
  readonly brown: AudioBuffer;
  /** One-shot nodes created so far (for CPU diagnostics). */
  nodes = 0;
  /** Milliseconds spent generating each bank (diagnostics). */
  readonly timings: Record<string, number> = {};
  private banks = new Map<string, AudioBuffer[]>();
  private jobs: (() => void)[] = [];

  constructor(
    readonly ctx: BaseAudioContext,
    seed: number,
  ) {
    const t0 = performance.now();
    this.rng = mulberry32(seed);
    const sr = ctx.sampleRate;
    const r = this.rng;
    const f = Math.floor(sr * 0.1);
    const loop = (d: Float32Array) => normRms(makeLoop(d, f), 0.25);
    this.white = this.buffer([loop(white(sr * 3 + f, r))], sr);
    this.pink = this.buffer([loop(pink(sr * 4 + f, r))], sr);
    this.pinkSt = this.buffer([loop(pink(sr * 6 + f, r)), loop(pink(sr * 6 + f, r))], sr);
    this.brown = this.buffer([loop(brown(sr * 5 + f, r))], sr);
    this.timings.noise = performance.now() - t0;
  }

  buffer(chs: Float32Array[], sr: number): AudioBuffer {
    const b = this.ctx.createBuffer(chs.length, chs[0].length, sr);
    chs.forEach((d, i) => b.copyToChannel(d as Float32Array<ArrayBuffer>, i));
    return b;
  }

  /** Queue `count` variations of a generated sound; `now` renders immediately. */
  bank(name: string, count: number, sr: number, gen: (r: Rng, sr: number) => Float32Array[], now = false): void {
    for (let i = 0; i < count; i++) {
      const job = () => {
        const t0 = performance.now();
        const list = this.banks.get(name) ?? [];
        list.push(this.buffer(gen(this.rng, sr), sr));
        this.banks.set(name, list);
        this.timings[name] = (this.timings[name] ?? 0) + performance.now() - t0;
      };
      if (now) job();
      else this.jobs.push(job);
    }
  }

  /** Queue arbitrary generation work. */
  defer(name: string, fn: () => void): void {
    this.jobs.push(() => {
      const t0 = performance.now();
      fn();
      this.timings[name] = (this.timings[name] ?? 0) + performance.now() - t0;
    });
  }

  /** Queue a multi-channel loop where each channel is generated by its own job. */
  loopBank(name: string, channels: number, sr: number, gen: (r: Rng, sr: number) => Float32Array[]): void {
    const chs: Float32Array[] = [];
    for (let c = 0; c < channels; c++)
      this.jobs.push(() => {
        const t0 = performance.now();
        chs.push(gen(this.rng, sr)[0]);
        if (chs.length === channels) this.banks.set(name, [this.buffer(chs, sr)]);
        this.timings[name] = (this.timings[name] ?? 0) + performance.now() - t0;
      });
  }

  /** Run queued generation jobs for up to `budgetMs`. Returns true when nothing is left. */
  pump(budgetMs: number): boolean {
    const t0 = performance.now();
    while (this.jobs.length) {
      this.jobs.shift()!();
      if (performance.now() - t0 > budgetMs) break;
    }
    return this.jobs.length === 0;
  }

  get pending(): number {
    return this.jobs.length;
  }

  has(name: string): boolean {
    return (this.banks.get(name)?.length ?? 0) > 0;
  }

  get(name: string): AudioBuffer[] {
    return this.banks.get(name) ?? [];
  }

  pick(name: string): AudioBuffer | null {
    const l = this.banks.get(name);
    return l && l.length ? l[Math.floor(this.rng() * l.length) % l.length] : null;
  }

  /** Looping source that starts immediately at a random offset. */
  loop(buf: AudioBuffer, rate = 1): AudioBufferSourceNode {
    const s = this.ctx.createBufferSource();
    s.buffer = buf;
    s.loop = true;
    s.playbackRate.value = rate;
    s.start(this.ctx.currentTime, this.rng() * buf.duration);
    return s;
  }

  /** Cheapest possible one-shot: a single source node straight into `dest`. */
  fire(buf: AudioBuffer, when: number, dest: AudioNode, rate = 1): void {
    const s = this.ctx.createBufferSource();
    s.buffer = buf;
    if (rate !== 1) s.playbackRate.value = rate;
    s.connect(dest);
    s.onended = () => s.disconnect();
    s.start(when);
    this.nodes++;
  }

  /** One-shot with gain, stereo placement (optionally drifting) and a reverb send. */
  play(buf: AudioBuffer, when: number, o: PlayOpts): void {
    const ctx = this.ctx;
    const s = ctx.createBufferSource();
    s.buffer = buf;
    const rate = Math.max(0.25, o.rate ?? 1);
    s.playbackRate.value = rate;
    const g = ctx.createGain();
    g.gain.value = o.gain ?? 1;
    const p = ctx.createStereoPanner();
    const pan = clampPan(o.pan ?? 0);
    p.pan.setValueAtTime(pan, when);
    if (o.panTo !== undefined) p.pan.linearRampToValueAtTime(clampPan(o.panTo), when + buf.duration / rate);
    s.connect(g).connect(p).connect(o.dest);
    let w: GainNode | null = null;
    if (o.wet && o.wetDest) {
      w = ctx.createGain();
      w.gain.value = o.wet;
      p.connect(w).connect(o.wetDest);
    }
    s.onended = () => {
      s.disconnect();
      g.disconnect();
      p.disconnect();
      w?.disconnect();
    };
    s.start(when);
    this.nodes += w ? 4 : 3;
  }
}

const clampPan = (p: number) => (p < -1 ? -1 : p > 1 ? 1 : Number.isFinite(p) ? p : 0);

/** Smoothly move an AudioParam toward `v` (NaN-safe). */
export function glide(p: AudioParam, v: number, now: number, tau: number): void {
  if (Number.isFinite(v)) p.setTargetAtTime(v, now, tau);
}

/**
 * A level control that disconnects its chain once it has faded to silence, so Web Audio stops pulling
 * (and computing) everything upstream; it reconnects from zero as soon as it is needed again.
 */
export class Gate {
  private on = true;
  private quietSince = -1;
  constructor(
    readonly g: GainNode,
    private readonly dest: AudioNode,
  ) {
    g.gain.value = 0;
    g.connect(dest);
  }
  set(v: number, now: number, tau: number): void {
    if (!Number.isFinite(v)) return;
    if (v > 1e-5) {
      if (!this.on) {
        this.g.gain.cancelScheduledValues(now);
        this.g.gain.setValueAtTime(0, now);
        this.g.connect(this.dest);
        this.on = true;
      }
      this.quietSince = -1;
      this.g.gain.setTargetAtTime(v, now, tau);
    } else if (this.on) {
      this.g.gain.setTargetAtTime(0, now, tau);
      if (this.quietSince < 0) this.quietSince = now;
      else if (now - this.quietSince > tau * 8 + 0.25) {
        this.g.disconnect();
        this.on = false;
      }
    }
  }
}

const stepped = new WeakMap<AudioParam, number>();
/**
 * Like `glide`, but smoothed in JS and applied as discrete steps at the ~30 Hz param rate. Use for filter
 * frequencies: a continuously automated biquad recomputes its coefficients every sample.
 */
export function glideStep(p: AudioParam, v: number, now: number, tau: number): void {
  if (!Number.isFinite(v)) return;
  const prev = stepped.get(p);
  const nv = prev === undefined ? v : prev + (v - prev) * (1 - Math.exp(-1 / 30 / tau));
  stepped.set(p, nv);
  if (prev === undefined || Math.abs(nv - prev) > Math.abs(prev) * 0.002) p.setValueAtTime(nv, now);
}

export abstract class Layer {
  /** Dry output of the layer. */
  readonly out: GainNode;
  /** Reverb send of the layer. */
  readonly wet: GainNode;
  protected readonly ctx: BaseAudioContext;
  constructor(protected readonly kit: Kit) {
    this.ctx = kit.ctx;
    this.out = kit.ctx.createGain();
    this.wet = kit.ctx.createGain();
  }
  /** Called every frame: schedule discrete events up to a short horizon. */
  abstract events(now: number, dt: number, s: RideState, e: Env): void;
  /** Called ~30×/s: steer continuous parameters. */
  abstract params(now: number, s: RideState, e: Env): void;

  protected filter(type: BiquadFilterType, f: number, q = 0.707): BiquadFilterNode {
    const b = this.ctx.createBiquadFilter();
    b.type = type;
    b.frequency.value = f;
    b.Q.value = q;
    return b;
  }
  protected gain(v = 0): GainNode {
    const g = this.ctx.createGain();
    g.gain.value = v;
    return g;
  }
  protected osc(f: number, type: OscillatorType = "sine"): OscillatorNode {
    const o = this.ctx.createOscillator();
    o.type = type;
    o.frequency.value = f;
    o.start();
    return o;
  }
}
