import * as THREE from 'three';

export function createEffects(scene) {
  const count=1100, positions=new Float32Array(count*3),colors=new Float32Array(count*3),alphas=new Float32Array(count);
  const items=Array.from({length:count},()=>({life:0,max:1,vx:0,vy:0,vz:0}));let cursor=0;
  const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(positions,3));geo.setAttribute('color',new THREE.BufferAttribute(colors,3));geo.setAttribute('particleAlpha',new THREE.BufferAttribute(alphas,1));
  const canvas=document.createElement('canvas');canvas.width=canvas.height=32;const ctx=canvas.getContext('2d'),gradient=ctx.createRadialGradient(16,16,0,16,16,16);gradient.addColorStop(0,'rgba(255,255,255,.8)');gradient.addColorStop(.3,'rgba(255,255,255,.45)');gradient.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=gradient;ctx.fillRect(0,0,32,32);
  const mat=new THREE.PointsMaterial({map:new THREE.CanvasTexture(canvas),size:1.2,transparent:true,depthWrite:false,vertexColors:true,opacity:.6});
  mat.onBeforeCompile=shader=>{shader.vertexShader=shader.vertexShader.replace('#include <common>','#include <common>\nattribute float particleAlpha; varying float vParticleAlpha;').replace('#include <begin_vertex>','#include <begin_vertex>\nvParticleAlpha = particleAlpha;');shader.fragmentShader=shader.fragmentShader.replace('#include <common>','#include <common>\nvarying float vParticleAlpha;').replace('#include <color_fragment>','#include <color_fragment>\ndiffuseColor.a *= vParticleAlpha;');};
  mat.customProgramCacheKey=()=>'wreckage-particle-alpha-v1';const points=new THREE.Points(geo,mat);points.frustumCulled=false;scene.add(points);
  const markGeo=new THREE.PlaneGeometry(.23,1.05);markGeo.rotateX(-Math.PI/2);const marks=new THREE.InstancedMesh(markGeo,new THREE.MeshBasicMaterial({color:0x29271e,transparent:true,opacity:.22,depthWrite:false}),1000);marks.frustumCulled=false;scene.add(marks);let markIndex=0;const dummy=new THREE.Object3D();dummy.scale.setScalar(0);dummy.updateMatrix();for(let i=0;i<1000;i++)marks.setMatrixAt(i,dummy.matrix);
  const chunks=new THREE.InstancedMesh(new THREE.BoxGeometry(.1,.12,.25),new THREE.MeshStandardMaterial({color:0x75694c,roughness:.7,metalness:.4}),100);chunks.frustumCulled=false;scene.add(chunks);const debris=Array.from({length:100},()=>({life:0,p:new THREE.Vector3(),v:new THREE.Vector3(),spin:0}));let chunkIndex=0;for(let i=0;i<100;i++)chunks.setMatrixAt(i,dummy.matrix);
  function puff(x,y,z,force=1,spark=false){const i=cursor++%count,a=items[i];a.life=a.max=spark?.25+Math.random()*.4:1+Math.random();a.vx=(Math.random()-.5)*force*4;a.vy=(spark?3:1)+Math.random()*force*2;a.vz=(Math.random()-.5)*force*4;positions[i*3]=x;positions[i*3+1]=y;positions[i*3+2]=z;a.spark=spark;}
  function impact(e){const force=Math.min(1,Math.max(.1,e.force||.3));for(let i=0;i<10+force*32;i++)puff(e.x,.6,e.z,force*3,i%3===0);for(let i=0;i<force*9;i++){const d=debris[chunkIndex++%100];d.life=3;d.p.set(e.x,.7,e.z);d.v.set((Math.random()-.5)*12,3+Math.random()*6,(Math.random()-.5)*12);d.spin=Math.random()*6;}}
  function update(dt,cars,active){
    for(const c of cars){if(active&&c.alive&&Math.abs(c.speed)>3&&Math.random()<dt*28){puff(c.x-Math.sin(c.yaw)*1.7,.15,c.z-Math.cos(c.yaw)*1.7,Math.abs(c.speed)*.025);if(Math.abs(c.steer)>.35&&Math.abs(c.speed)>7){for(const side of [-1,1]){dummy.position.set(c.x+Math.cos(c.yaw)*side*.83,.024,c.z-Math.sin(c.yaw)*side*.83);dummy.rotation.set(0,c.yaw,0);dummy.scale.set(1,1,1);dummy.updateMatrix();marks.setMatrixAt(markIndex++%1000,dummy.matrix);}marks.instanceMatrix.needsUpdate=true;}}if(c.health<35&&Math.random()<dt*15)puff(c.x+Math.sin(c.yaw)*1.1,1.25,c.z+Math.cos(c.yaw)*1.1,.3);}
    for(let i=0;i<count;i++){const a=items[i];a.life-=dt;if(a.life>0){positions[i*3]+=a.vx*dt;positions[i*3+1]+=a.vy*dt;positions[i*3+2]+=a.vz*dt;a.vy-=dt*(a.spark?8:.25);alphas[i]=Math.min(1,a.life/a.max*2);colors[i*3]=a.spark?1:.58;colors[i*3+1]=a.spark?.68:.48;colors[i*3+2]=a.spark?.2:.34;}else{positions[i*3+1]=-100;alphas[i]=0;}}
    for(let i=0;i<debris.length;i++){const d=debris[i];d.life-=dt;if(d.life>0){d.v.y-=dt*15;d.p.addScaledVector(d.v,dt);if(d.p.y<.1){d.p.y=.1;d.v.y=Math.abs(d.v.y)*.25;d.v.x*=.9;d.v.z*=.9;}dummy.position.copy(d.p);dummy.rotation.set(d.spin*d.life,d.life*2,0);dummy.scale.setScalar(Math.min(1,d.life));}else dummy.scale.setScalar(0);dummy.updateMatrix();chunks.setMatrixAt(i,dummy.matrix);}chunks.instanceMatrix.needsUpdate=true;geo.attributes.position.needsUpdate=true;geo.attributes.color.needsUpdate=true;geo.attributes.particleAlpha.needsUpdate=true;
  }
  function reset(){for(const a of items)a.life=0;for(const d of debris)d.life=0;dummy.scale.setScalar(0);dummy.updateMatrix();for(let i=0;i<1000;i++)marks.setMatrixAt(i,dummy.matrix);marks.instanceMatrix.needsUpdate=true;}
  return {update,impact,reset};
}
